import { CoverType, MyCoverType } from '@/screen/purchase/types';

export const filters = [
  'all cover product',
  'slashing',
  'smart contract risks',
  'protocol risks',
  'stable coin',
];

export const covers: CoverType[] = [
  {
    id: 1,
    logo: '',
    name: 'Aave V2',
    image: '',
    detail: 'Smart Contract Vulnerability',
    items: [
      'chains',
      'daily cost',
      'capacity',
      'security rating',
      'cover wording',
    ],
  },
  {
    id: 2,
    logo: '',
    name: 'Aave V2',
    image: '',
    detail: 'Smart Contract Vulnerability',
    items: [
      'chains',
      'daily cost',
      'capacity',
      'security rating',
      'cover wording',
    ],
  },
  {
    id: 3,
    logo: '',
    name: 'Aave V2',
    image: '',
    detail: 'Smart Contract Vulnerability',
    items: [
      'chains',
      'daily cost',
      'capacity',
      'security rating',
      'cover wording',
    ],
  },
  {
    id: 4,
    logo: '',
    name: 'Aave V2',
    image: '',
    detail: 'Smart Contract Vulnerability',
    items: [
      'chains',
      'daily cost',
      'capacity',
      'security rating',
      'cover wording',
    ],
  },
  {
    id: 5,
    logo: '',
    name: 'Aave V2',
    image: '',
    detail: 'Smart Contract Vulnerability',
    items: [
      'chains',
      'daily cost',
      'capacity',
      'security rating',
      'cover wording',
    ],
  },
  {
    id: 6,
    logo: '',
    name: 'Aave V2',
    image: '',
    detail: 'Smart Contract Vulnerability',
    items: [
      'chains',
      'daily cost',
      'capacity',
      'security rating',
      'cover wording',
    ],
  },
];

export const myCovers: MyCoverType[] = [
  {
    id: 1,
    logo: '',
    name: 'Aave V2',
    image: '',
    detail: 'Smart Contract Vulnerability',
    value: ' 2WBTC',
    expiry: '12.12.2024',
  },
  {
    id: 1,
    logo: '',
    name: 'Aave V2',
    image: '',
    detail: 'Smart Contract Vulnerability',
    value: ' 2WBTC',
    expiry: '12.12.2024',
  },
  {
    id: 1,
    logo: '',
    name: 'Aave V2',
    image: '',
    detail: 'Smart Contract Vulnerability',
    value: ' 2WBTC',
    expiry: '12.12.2024',
  },
  {
    id: 1,
    logo: '',
    name: 'Aave V2',
    image: '',
    detail: 'Smart Contract Vulnerability',
    value: ' 2WBTC',
    expiry: '12.12.2024',
  },
  {
    id: 1,
    logo: '',
    name: 'Aave V2',
    image: '',
    detail: 'Smart Contract Vulnerability',
    value: ' 2WBTC',
    expiry: '12.12.2024',
  },
  {
    id: 1,
    logo: '',
    name: 'Aave V2',
    image: '',
    detail: 'Smart Contract Vulnerability',
    value: ' 2WBTC',
    expiry: '12.12.2024',
  },
];
